fix: et-4736 added test for secret value

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,3 +20,8 @@ jobs:
         masked: true
     - name: show environment
       run: env | grep TEST_
+
+    - name: test secret value
+      run: |
+        echo check if test secret equals to 4 9s
+        [ "$TEST_SECRET" == "9999" ] && echo "TEST_SECRET valid" || echo "TEST_SECRET invalid"
